-- WARNING : DO NOT MESS WITH.
--THIS FILE HAS BEEN AUTOGENERATED BY ArborLuaBindingsGenerator.cs.

GameManagerAPI={};
GameManagerAPI.add_OnInitGame=function(value__EventHandler)end
GameManagerAPI.remove_OnInitGame=function(value__EventHandler)end
GameManagerAPI.add_OnStartGame=function(value__EventHandler)end
GameManagerAPI.remove_OnStartGame=function(value__EventHandler)end
GameManagerAPI.add_OnRunGame=function(value__EventHandler)end
GameManagerAPI.remove_OnRunGame=function(value__EventHandler)end
GameManagerAPI.add_OnStopGame=function(value__EventHandler)end
GameManagerAPI.remove_OnStopGame=function(value__EventHandler)end
GameManagerAPI.add_OnCloseGame=function(value__EventHandler)end
GameManagerAPI.remove_OnCloseGame=function(value__EventHandler)end
GameManagerAPI.RaiseOnInitGame=function()end
GameManagerAPI.RaiseOnStartGame=function()end
GameManagerAPI.RaiseOnRunGame=function()end
GameManagerAPI.RaiseOnStopGame=function()end
GameManagerAPI.RaiseOnCloseGame=function()end
GameManagerAPI.Clear=function()end
